// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/// @notice EVM Poseidon over BN254, circomlib-compatible (== noir-lang/poseidon
///         used by the will circuit). Deployed from bytecode generated by
///         circomlibjs `poseidon_gencontract`; see contracts/poseidon/.

/// @dev t=3 permutation: hash of 2 field elements.
interface IPoseidonT3 {
    function poseidon(bytes32[2] calldata input) external view returns (bytes32);
}

/// @dev t=5 permutation: hash of 4 field elements.
interface IPoseidonT5 {
    function poseidon(bytes32[4] calldata input) external view returns (bytes32);
}
