// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import {HonkVerifier} from "../src/HonkVerifier.sol";
import {WillVerifier} from "../src/WillVerifier.sol";

/**
 * @title WillVerifierTest
 * @notice Proves the on-chain verification path is REAL: a genuine UltraHonk
 *         proof for the will circuit (generated by `bb prove` against
 *         noir/will/target/will.json) verifies through
 *         WillVerifier -> HonkVerifier, and any tampering fails.
 *
 * Fixtures in test/fixtures/ are the exact artifacts from:
 *   bb prove -b will.json -w will.gz -k vk -o proof --verifier_target evm-no-zk --scheme ultra_honk
 *   - will_proof.bin         = proof/proof         (raw UltraHonk proof bytes)
 *   - will_public_inputs.bin = proof/public_inputs (5 x bytes32, frozen order)
 *
 * Non-ZK, not the `evm` (ZK) target: as of bb.js (Aztec's Barretenberg JS
 * package) version 5.1.0, in-browser proving produces a different (longer)
 * proof for the ZK target than the native `bb` CLI does for the identical
 * circuit — a confirmed native/bb.js discrepancy, not an application bug.
 * The non-ZK target's output matches byte-for-byte between native bb and
 * bb.js, so the verifier targets it too.
 */
contract WillVerifierTest is Test {
    HonkVerifier internal honk;
    WillVerifier internal willVerifier;

    bytes internal proof;
    uint256[5] internal publicInputs;

    function setUp() public {
        honk = new HonkVerifier();
        willVerifier = new WillVerifier(address(honk));

        proof = vm.readFileBinary("test/fixtures/will_proof.bin");

        bytes memory pub = vm.readFileBinary("test/fixtures/will_public_inputs.bin");
        require(pub.length == 160, "expected 5 x 32-byte public inputs");
        for (uint256 i = 0; i < 5; i++) {
            uint256 v;
            // word i starts at offset 0x20 (length slot) + i*0x20
            assembly {
                v := mload(add(add(pub, 0x20), mul(i, 0x20)))
            }
            publicInputs[i] = v;
        }
    }

    /// Sanity: fixtures decode to the circuit's known test vector.
    function test_FixturePublicInputsAreExpected() public view {
        assertEq(publicInputs[2], 10, "total_eth");
        assertEq(publicInputs[3], 1000, "total_usdc");
        assertEq(publicInputs[4], 2, "total_nft_count");
    }

    /// A real proof verifies through the will adapter.
    function test_ValidProofVerifies() public view {
        assertTrue(
            willVerifier.verifyProof(proof, publicInputs),
            "valid proof must verify"
        );
    }

    /// The named-parameter overload verifies identically.
    function test_ValidProofVerifiesNamedOverload() public view {
        assertTrue(
            willVerifier.verifyWillProof(
                proof,
                publicInputs[0],
                publicInputs[1],
                publicInputs[2],
                publicInputs[3],
                publicInputs[4]
            ),
            "valid proof must verify via named overload"
        );
    }

    /// Wrong public inputs (right proof) must not verify — the proof is bound
    /// to its exact public inputs. bb's verifier reverts on a public-input
    /// mismatch, so we assert the call fails rather than returns false.
    function test_WrongPublicInputFails() public {
        uint256[5] memory tampered = publicInputs;
        tampered[2] = publicInputs[2] + 1; // claim a different total_eth
        vm.expectRevert();
        willVerifier.verifyProof(proof, tampered);
    }

    /// A corrupted proof must not verify (reverts inside the verifier).
    function test_TamperedProofReverts() public {
        bytes memory bad = proof;
        bad[64] = bytes1(uint8(bad[64]) ^ 0xFF); // flip a byte in a proof field
        vm.expectRevert();
        willVerifier.verifyProof(bad, publicInputs);
    }

    /// A public input at/above the BN254 field modulus is rejected up front.
    function test_OutOfFieldPublicInputReverts() public {
        uint256 fieldModulus =
            0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001;
        uint256[5] memory bad = publicInputs;
        bad[0] = fieldModulus; // exactly the modulus -> not a valid field element
        vm.expectRevert(
            abi.encodeWithSelector(WillVerifier.PublicInputNotInField.selector, uint256(0))
        );
        willVerifier.verifyProof(proof, bad);
    }

    /// The adapter rejects a zero verifier address at construction.
    function test_ConstructorRejectsZeroAddress() public {
        vm.expectRevert(WillVerifier.InvalidVerifierAddress.selector);
        new WillVerifier(address(0));
    }
}
